CREATE TABLE CLIENTES(
	ID_CLIENTE INT PRIMARY KEY NOT NULL,
	NOME_CLIENTE VARCHAR(50) NOT NULL,
	CPF_CLIENTE VARCHAR(8) UNIQUE NOT NULL,
	RUA_END VARCHAR(50) NOT NULL,
	NUMERO_END VARCHAR(50) NOT NULL,
	COMPLEMENTO_END VARCHAR (6),
	BAIRRO_END VARCHAR(30) NOT NULL,
	MUNICIPIO_END VARCHAR(30) NOT NULL,
	CEP_END CHAR(8) NOT NULL,
	UF_END CHAR(2) NOT NULL
);